Repository OpenSourceRaidGuild/Guild-Scrivener, pull requests merged in 2021-02, with the labels that each got.

#10 Jacobmgevans
  package-lock.json
  package.json
  src/labels/index.ts
  src/labels/labelling.ts
  src/labels/types.ts
  src/octokit.ts
  src/raids/completeRaid.ts
  src/raids/newRaid.ts
  src/raids/statCompactor.ts
  tsconfig.json
Labels: Type: Enhancement, Type: Refactor, Type: Toolchain

#16 test: stat compactor
  src/raids/completeRaid.test.ts
  src/raids/newRaid.test.ts
  src/raids/statCompactor.test.ts
  src/testUtils/dataFactory.ts
  src/testUtils/msw/handlers.ts
Labels: Difficulty: Mythic, Priority: Critical, Type: Feature

#20 module for the helpers to reuse in init mass update
  labels-local.json
  package-lock.json
  package.json
  repos-local.js
  src/index.ts
  src/labels/index.ts
  src/labels/initLabelsInNewRepo.ts
  src/labels/labelWebhookHandler.test.ts
  src/labels/labelWebhookHandler.ts
  src/labels/labelling.ts
  src/labels/repoEventHelpers.ts
  src/labels/types/labels.ts
  src/raids/completeRaid.test.ts
  src/raids/completeRaid.ts
  src/raids/newRaid.test.ts
  src/raids/newRaid.ts
  src/raids/statCompactor.test.ts
  src/raids/statCompactor.ts
  src/testUtils/dataFactory/index.ts
Labels: Difficulty: Hardmode, Items: Epic, Priority: Low 🍃, Type: Feature
